id = "vuex-helper"
name = "Vuex Helper"
version = "0.1.1"
schema_version = 1
authors = ["dmxiaoshubao"]
description = "Vuex definition, completion, hover, and diagnostics support through vuex-helper LSP."
repository = "https://github.com/dmxiaoshubao/vuex-helper-for-zed"

[language_servers.vuex-helper]
name = "Vuex Helper LSP"
languages = ["Vue.js", "JavaScript", "TypeScript"]
